### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by francescobigoni**

### CODE REVIEW

**Comment by francescobigoni** [comment]
Added demo of Karplus-Strong, clarinet and flute models with MIDI functionality and polyphony.

**Comment by francescobigoni** [comment]
Added Karplus-Strong, clarinet and flute demo with MIDI and polyphony.

**Comment by francescobigoni** [comment]
Added Karplus-Strong, clarinet and flute demo with MIDI and polyphony.

**Comment by NikolajAndersson** [comment]
Looks good!

**Pull request merged**
